apiVersion: v1
kind: Service
metadata:
  name: course-app-svc
  namespace: mod04-less13
  labels:
    app: course-app
spec:
  type: ClusterIP
  selector:
    app: course-app
  ports:
    - port: 8080 
      targetPort: 8080 
      protocol: TCP
      name: course-app
