apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rd
  name: lesson-8
  labels:
    app: lesson-8
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lesson-8
  template:
    metadata:
      name: lesson-8
      labels:
        app: lesson-8
    spec:
      containers:
        - name: lesson-8
          image: vitaliyavramenko/lesson-6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              port: 8080
              path: /readyz
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
      restartPolicy: Always
