services:
  app:
    build:
      context: ./apps/course-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_MESSAGE=Welcome to the Course Application!
    networks:
      - db
      - app
    depends_on:
      dblite:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: "redis:alpine"
    environment:
      - APP_STORE=redis
      - APP_REDIS_URL=redis://redis:6379/0
    volumes:
      - app-data:/data
    networks:
      - db
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
      
  dblite:
    image: "klee/sqlite:3400100_ubuntu_jammy-20230126"
    command: ["sleep", "infinity"]
    environment:
      - APP_DB_PATH=/data/app.db
    networks:
      - db
    ports:
      - "8080:8080"
    volumes:
      - dbl-data:/data
    healthcheck:
      test: ["CMD-SHELL", "test -f /app/data/your_database.db && echo 'SELECT 1;' | sqlite3 /app/data/your_database.db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  db:
    driver: bridge
  app:
    driver: bridge

volumes:
  app-data:
  dbl-data:
