version: "3.9"

services:
  app:
    build:
      context: /Users/andreqko/Documents/WebstormProjects/docker_and_kuber/apps/course-app
      dockerfile: /Users/andreqko/Documents/WebstormProjects/docker_and_kuber/homeworks/stepanov/module-2/lesson-04/Dockerfile
    ports:
      - "8080:8080"
    environment:
      APP_STORE: redis
      APP_REDIS_URL: redis://redis:6379/0
  redis:
    image: redis:7-alpine
