apiVersion: v1
kind: ConfigMap
{{ include "lab.metadata" . }}
data:
  APP_MESSAGE: "Hello, Robot Dreams!"
  APP_STORE: {{ .Values.redis.enable | ternary "redis" "sqlite" | quote }}
  APP_REDIS_URL: "redis://{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}.svc.cluster.local:6379"