apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-viewer
  namespace: krotovhh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: db-readonly
  namespace: krotovhh
rules:
- apiGroups: ["dragonflydb.io"]
  resources:
    - dragonflies
  verbs:
    - get
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: db-readonly-binding
  namespace: krotovhh
subjects:
- kind: ServiceAccount
  name: db-viewer
  namespace: krotovhh
roleRef:
  kind: Role
  name: db-readonly
  apiGroup: rbac.authorization.k8s.io