apiVersion: v1
kind: Service
metadata:
  name: course-app-service
spec:
  type: NodePort
  selector:
    app: course-app
  ports:
    - protocol: TCP
      nodePort: 30080
      port: 80
      targetPort: 8080
