apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "course-app.fullname" . }}-config-map
data:
  APP_MESSAGE: {{ .Values.appMessage }}
  APP_STORE: {{ .Values.appStore }}
  APP_REDIS_URL: {{ .Values.redisURL }}
