services:
  app:
    build:
      context: ../../../..
      dockerfile: ./homeworks/v.voitenko/module-2/lesson-04/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      -   redis
    environment:
      - APP_MESSAGE="Welcome to the Course App"
      - APP_STORE=redis
      - APP_REDIS_URL=redis://redis:6379/0
    restart: unless-stopped
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
