apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "course-app.fullname" . }}
  labels:
    {{- include "course-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy: {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "course-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "course-app.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: check-redis-ready
        image: busybox:stable
        command: ['sh', '-c', 'until nslookup {{ .Values.redis.host }}; do echo waiting for redis; sleep 2; done;']
      
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP

        livenessProbe:
          httpGet:
            path: {{ .Values.probes.liveness.path }}
            port: {{ .Values.probes.liveness.port }}
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}

        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readiness.path }}
            port: {{ .Values.probes.readiness.port }}
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}

        resources:
          {{- toYaml .Values.resources | nindent 10 }}

        env:
        - name: APP_STORE
          value: "redis"
        - name: APP_REDIS_HOST
          value: {{ .Values.redis.host | quote }}
        - name: APP_REDIS_PORT
          value: {{ .Values.redis.port | quote }}
#        - name: REDIS_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: course-app-redis
#              key: redis-password

        - name: APP_MESSAGE
          value: "Helm Chart Deployment v1.0"