apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-app-deployment
  namespace: mod03-less06
  labels:
    app: course-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-app
  template:
    metadata:
      labels:
        app: course-app
    spec:
      containers:
        - name: course-app
          image: rdlsolutions/course-app:1.0.5
          resources:
            requests:
              cpu: "100m"  
              memory: "64Mi" 
            limits:
              cpu: "200m"  
              memory: "512Mi" 
          ports:
            - containerPort: 8080
          env:
            - name: APP_MESSAGE
              value: "Welcome to the Course Application!"
            - name: APP_REDIS_URL
              value: "redis://redis:30079/0"
            - name: APP_DB_PATH
              value: "/data/app.db"
            - name: APP_STORE
              value: "redis"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "30079" 
          volumeMounts:
            - name: dbl-data
              mountPath: /data
      volumes:
        - name: dbl-data
          persistentVolumeClaim:
            claimName: dbl-data-claim
