apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-app
  labels:
    app: capp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capp
  template:
    metadata:
      labels:
        app: capp
    spec:
      containers:
      - name: course-app
        image: malskur/capp:latest
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 400m
            memory: 512Mi