apiVersion: v1
kind: Service
metadata:
  name: cource-app
spec:
  selector:
    app: capp
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30088