apiVersion: v1
kind: Namespace
metadata:
  name: course-app-dev
  labels:
    environment: dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: course-app-config-map
  namespace: course-app-dev
data:
  HELLO_MESSAGE: "Hello, it's homework from Kyrylo Meretskyi!"
