services:
  app:
    build:
      context: ../../../../
      dockerfile: homeworks/kalinovsky/module-02/lesson-04/Dockerfile
    ports:
      - "8080:8000"
    container_name: course_app
    environment:
      APP_STORE: redis
      APP_REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_app
    ports:
      - "6379:6379"