apiVersion: apps/v1
kind: Deployment
metadata:
  name: snak-app-deployment
  labels:
    app: snak-app
spec:
  replicas: 7
  selector:
    matchLabels:
      app: snak-app
  template:
    metadata:
      labels:
        app: snak-app
    spec:
      containers:
        - name: snak-app-container
          image: andreqko/snak-app:latest
          ports:
            - containerPort: 8080
