apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-app-deployment
  namespace: course-app-dev
  labels:
    app: course-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: course-app
  template:
    metadata:
      labels:
        app: course-app
    spec:
      containers:
        - name: course-app
          image: kyrops/course-app:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: course-app-config-map
                  key: REVERSED_HELLO_MESSAGE
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxSurge: 2
#      maxUnavailable: 3

  strategy:
    type: Recreate
