apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "lesson-11.fullname" . }}
  labels:
    {{- include "lesson-11.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:    
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ include "lesson-11.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "lesson-11.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}