services:
  course-app:
    build:
      context: ../../../../apps/course-app/
      dockerfile: ../../homeworks/chornonoh/module-02/lesson-04/Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - APP_MESSAGE=Hello World!
      - APP_STORE=redis
      - APP_REDIS_URL=redis://database:6379/0
    networks:
      - app
      - database

  database:
    image: redis:8.2.3
    volumes:
      - db_data:/data
    networks:
      - database

volumes:
  db_data:

networks:
  app:
  database:

