apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "course-app.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "course-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  APP_STORE: {{ .Values.config.appStore | quote }}
  APP_REDIS_URL: {{ printf "redis://%s:%d/%d" .Values.config.redis.host (int .Values.config.redis.port) (int .Values.config.redis.db) | quote }}