apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  namespace: {{ .Values.global.namespace }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.tls.dns }}
      secretName: course-app-tls
  rules:
    - host: {{ .Values.ingress.tls.dns }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: course-app
                port:
                  number: 8080
