apiVersion: v1
kind: Service
metadata:
  name: course-app-service
spec:
  type: ClusterIP           
  selector:
    app: course-app        # Шукає поди з такою міткою (з Deployment) - P.S помічаю для себе
  ports:
    - protocol: TCP
      port: 80             # Порт всередині кластера
      targetPort: 8080     # Порт контейнера
