apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rd
  name: course-app
  labels:
    app: course-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-app
  template:
    metadata:
      name: course-app
      labels:
        app: course-app
    spec:
      serviceAccountName: db-viewer
      containers:
        - name: course-app
          image: vitaliyavramenko/lesson-6:1
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_STORE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_STORE
            - name: APP_REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_REDIS_URL
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
