apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dragonfly-operator-system
  name: app-binding
subjects:
  - kind: ServiceAccount
    name: db-viewer
    namespace: rd
roleRef:
  kind: Role
  name: db-readonly
  apiGroup: rbac.authorization.k8s.io

