{{- if .Values.rbac.enabled -}}
---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "course-app.labels" . | nindent 4 }}

---
# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.role.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "course-app.labels" . | nindent 4 }}
rules:
- apiGroups: ["dragonflydb.io"]
  resources: ["dragonflies"]
  verbs: ["get", "list", "watch"]

---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.serviceAccount.name }}-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "course-app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rbac.role.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}
