apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "course-app.fullname" . }}-config
data:
  APP_STORE: "redis"
  APP_REDIS_URL: {{ printf "redis://%s:%d/0" 
    (include "course-app.redisHost" .) 
    (include "course-app.redisPort" . | int)
  | quote }}
  APP_MESSAGE: {{ .Values.app.message | quote }}
