apiVersion: v1
kind: Service
metadata:
  name: {{ include "course-app.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "course-app.name" . }}
  ports:
    - port: 8080
      targetPort: 8080
