apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_MESSAGE: "Course App by Andrii Kharkovyi 111"
  APP_STORE: "sqlite"
  APP_DB_PATH: "/data/app.db"
  APP_REDIS_URL: "redis://course-redis:6379/0"