apiVersion: v1
kind: Service
metadata:
  name: course-app-andrii-kharkovyi-service
  labels:
    app: course-app-andrii-kharkovyi
spec:
  type: ClusterIP
  selector:
    app: course-app-andrii-kharkovyi
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http