services:
  backend:
    image: course-app:v1.0 
    ports:
      - "8080:8080"
    environment:
      - APP_MESSAGE=Hello World!
      - APP_STORE=redis
      - APP_REDIS_URL=redis://redis:6379/0 
    depends_on:
       redis:
           condition: service_healthy 
    healthcheck:
       test: ["CMD", "curl", "-sf", "http://localhost:8080/healthz"]
  redis:
    image:  ${CORP_REGISTRY}/redis:8
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - appdata:/data
volumes:
  appdata:
