apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: course-app-traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - capp.local
    secretName: capp-tls-secret
  rules:
  - host: capp.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: course-app
            port:
              number: 8080