apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-dev
  namespace: flux-system
spec:
  interval: 1m0s 
  path: "./clusters/course-app/overlays/development"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system