apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  APP_STORE: "redis"
#   APP_REDIS_URL: "redis://redis.rd.svc.cluster.local:6379/0"
  APP_REDIS_URL: "redis://redis:6379/0"
  APP_MESSAGE: "hello world)"
