apiVersion: v1
kind: ConfigMap
metadata:
  name: course-app-config-map
  namespace: lesson-12
data:
  APP_STORE: "redis"
  APP_REDIS_URL: "redis://dragonfly-sample.lesson-12:6379/0"
  APP_MESSAGE: "Hello World"
