apiVersion: v1
kind: Service
metadata:
  name: {{ include "course-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "course-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "course-app.selectorLabels" . | nindent 4 }}