services:
  web:
    build:
      context: ../../../../
      dockerfile: homeworks/shchekotov/module-02/lesson-04/Dockerfile
    env_file:
        - course-app.env
    ports:
      - "8080:8080"
    networks:
      - course-app-network
  redis:
    image: redis:8.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - course-app-network

networks:
  course-app-network:
    driver: bridge

volumes:
  redis_data: