replicaCount: 1

image:
  repository: my-build
  pullPolicy: IfNotPresent
  tag: "2.0"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  host: course-app.127.0.0.1.sslip.io
  tls:
    enabled: true
    secretName: course-app-tls


env:
  APP_STORE: "redis"
  APP_REDIS_URL: "redis://dragonfly-sample:6379"

redis:
  enabled: false