apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}-container
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.app.name }}-config
          {{- if .Values.app.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.app.service.port }}
            initialDelaySeconds: {{ .Values.app.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.app.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.app.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.app.probes.readiness.failureThreshold }}
          {{- end }}
          {{- if .Values.app.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.app.service.port }}
            initialDelaySeconds: {{ .Values.app.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.app.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.app.probes.liveness.failureThreshold }}
          {{- end }}
