---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "python-course-app-lesson10"
  name: "python-course-app-lesson10-service"
  namespace: krotovhh
spec:
  type: ClusterIP
  selector:
    app: "python-course-app-lesson10"
  ports:
  - name: python-course-app-lesson10-service
    port: 80
    protocol: TCP
    targetPort: 8080
...

