---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "redis7"
  name: "redis7"
  namespace: krotovhh
spec:
  selector:
    app: "redis7"

  type: ClusterIP
  ports:
  - name: service
    
    port: 6379
    protocol: TCP
    targetPort: 6379
...
