apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "course-app.fullname" . }}-deployment
  labels:
    app: {{ include "course-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "course-app.fullname" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ include "course-app.fullname" . }}
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z {{ .Values.redis.host }} {{ .Values.redis.port }}; do
                echo "Waiting for Redis...";
                sleep 2;
              done
      containers:
        - name: course-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "course-app.fullname" . }}-config
          env:
            - name: APP_STORE
              value: "redis"
            - name: APP_REDIS_URL
              value: "redis://{{ .Values.redis.host }}:{{ .Values.redis.port }}/0"
            - name: APP_DB_PATH
              value: "/data/app.db"
          volumeMounts:
            - name: appdata
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: appdata
          emptyDir: {}
