apiVersion: v1
kind: Service
metadata:
  name: {{ include "course-app.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "course-app.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
