services:
  python:
    image: $IMAGE_NAME:$IMAGE_TAG
    build:
      dockerfile: $PWD/Dockerfile
      context: $SRC_PATH
      args:
        ENV_VERSION: $SRC_ENV_VERSION
    ports:
      - "$APP_EXT_PORT:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080/healthz | jq -e '.status == \"ok\"' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - redis
    environment:
      - APP_MESSAGE=Robot Dreams - Lesson 04/05
      - APP_STORE=redis
      - APP_REDIS_URL=redis://:$REDIS_PASSWORD@redis:6379/0

  redis:
    image: redis:alpine
    command: "redis-server --requirepass $REDIS_PASSWORD"
    #ports:
    #  - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped