apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "course-app.fullname" . }}
  labels:
    {{- include "course-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "course-app.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.app.strategy.type }}
    {{- if eq .Values.app.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.app.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.app.strategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    metadata:
      labels:
        {{- include "course-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.service.port }}
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "course-app.fullname" . }}-config
          livenessProbe:
            httpGet:
              path: {{ .Values.app.livenessProbe.httpGet.path }}
              port: {{ .Values.app.livenessProbe.httpGet.port }}
              scheme: {{ .Values.app.livenessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.app.livenessProbe.successThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.app.readinessProbe.httpGet.path }}
              port: {{ .Values.app.readinessProbe.httpGet.port }}
              scheme: {{ .Values.app.readinessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.app.readinessProbe.successThreshold }}
          resources:
            requests:
              memory: {{ .Values.app.resources.requests.memory | quote }}
              cpu: {{ .Values.app.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.app.resources.limits.memory | quote }}
              cpu: {{ .Values.app.resources.limits.cpu | quote }}