apiVersion: v1
kind: Service
metadata:
  name: {{ include "course-app.fullname" . }}-service
  labels:
    {{- include "course-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    {{- include "course-app.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.port }}
      protocol: TCP
      name: http