apiVersion: v1
kind: Service
metadata:
  name: course-app
  namespace: dev
  labels:
    app: course-app
spec:
  type: NodePort
  selector:
    app: course-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080