services:
  course-app:
    build:
      context: ../../../..
      dockerfile: homeworks/perkhun/module-2/lesson-04/Dockerfile
    container_name: course-app
    ports:
      - "8080:8080"
    environment:
      APP_STORE: redis
      APP_REDIS_URL: redis://redis:6379/0
      APP_MESSAGE: "Hello from Compose"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
