name: course-app

services:
  app:
    image: mmykhailenko/lesson-04:dev
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - cache
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-q", "http://localhost:8080/healthz" ]
      interval: 15s
      timeout: 1s
      retries: 5
    restart: always
    env_file:
      .env

  redis:
    image: redis:8.2.3-alpine3.22
    command: [ "redis-server", "--save", "60", "1" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 15s
      timeout: 1s
      retries: 5
    networks:
      - cache
    volumes:
      - redis_cache:/data

networks:
  cache:
    driver: bridge

volumes:
  redis_cache:

