apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: lesson-08
data:
  TZ: "Europe/Kiev"
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  APP_LANGUAGE: "en_US:en"
  APP_MESSAGE: "Robot Dreams - Lesson 08"
  APP_STORE: "redis"