apiVersion: v1
kind: Service
metadata:
  name: {{ include "course-app.fullname" . }}
  labels:
    {{- include "course-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "course-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080