services:
  python:
    image: $IMAGE_NAME:$IMAGE_TAG
    build:
      dockerfile: $PWD/Dockerfile
      context: $SRC_PATH
      args:
        ENV_VERSION: $SRC_ENV_VERSION
    ports:
      - "$APP_EXT_PORT:8080"
    depends_on:
      - redis
    environment:
      - APP_MESSAGE=Robot Dreams - Lesson 04
      - APP_STORE=redis
      - APP_REDIS_URL=redis://:$REDIS_PASSWORD@redis:6379/0

  redis:
    image: redis:alpine
    command: "redis-server --requirepass $REDIS_PASSWORD"
    #ports:
    #  - "6379:6379"
    restart: unless-stopped