apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-course-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-course-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-course-app
    spec:
      containers:
        - name: course-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: APP_STORE
              value: "redis"
            - name: APP_REDIS_URL
              value: "redis://redis-master:6379"