apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-configmap
  namespace: {{ .Values.namespace }}
data:
  APP_STORE: "redis"
  APP_REDIS_URL: "redis://{{ .Release.Name }}-redis-master:6379"
  APP_MESSAGE: "Hello, Helm!"
