apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-sv
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "app.lables" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.app.containerPort }}
      protocol: TCP
