services:
  backend:
    image: course-app:v1.0 
    ports:
      - "8080:8080"
    environment:
      - APP_MESSAGE=Hello World!
      - APP_STORE=redis
      - APP_REDIS_URL=redis://redis:6379/0 
    depends_on:
      - redis
  redis:
    image:  ${CORP_REGISTRY}/redis:8
