apiVersion: v1
kind: ConfigMap
metadata:
  name: course-app-config-map
data:
  APP_MESSAGE: "Welcome to the Course App 2"
  APP_STORE: "redis"
  APP_REDIS_URL: "redis://course-app-redis.default.svc.cluster.local:6379/0"
