apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-configmap
  namespace: {{ .Values.namespace }}
data:
  APP_STORE: "{{ .Values.configMap.appStore }}"
  APP_REDIS_URL: "{{ .Values.configMap.appRedisUrl }}"
  APP_MESSAGE: "{{ .Values.configMap.appMessage}}"
