apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "course-app.fullname" . }}-ingress
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - course-app.local
    secretName: course-app-tls
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "course-app.fullname" . }}
            port:
              number: {{ .Values.servicePort }}
