apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: hw10
data:
  APP_NAME: "Course App hw07-NEW"
  APP_LOG_LEVEL: "debug"
  APP_TIMEOUT: "5s"
  APP_STORE: redis
  APP_REDIS_URL: redis://redis:6379/0
