apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: robot-dreams
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: course-app
          image: kusandr0/robot_dreams_app:06-alpine
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: "Europe/Kiev"
            - name: LANG
              value: "en_US.UTF-8"
            - name: LC_ALL
              value: "en_US.UTF-8"
            - name: LANGUAGE
              value: "en_US:en"
            - name: APP_MESSAGE
              value: "Robot Dreams - Lesson 06"
            - name: "APP_STORE"
              value: "redis"
            - name: "APP_REDIS_URL"
              value: "redis://redis-svc:6379/0"