apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: course-app-motilevskiy
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
        - test.example.loc
      secretName: course-app-motilevskiy-tls
  rules:
    - host: test.example.loc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: course-app-motilevskiy
                port:
                  number: 8080
