apiVersion: v1
kind: ConfigMap
metadata:
  name: course-app-config
  namespace: course-app-dev
data:
  APP_STORE: "redis"
  APP_REDIS_URL: "redis://redis-course-app-svc:6379/0"
  APP_MESSAGE: "Docker and Kubetnetis Course App Hello Viktor - Config Updated"
