---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "python-course-app"
  name: "python-course-app-service"
  namespace: krotovhh
spec:
  ports:
  - name: service
    
    nodePort: 30001
    
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
  
  selector:
    app: "python-course-app"
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600  
...

