apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-app-deployment
  namespace: course-app-dev
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 20%
  selector:
    matchLabels:
      app: course-app
  template:
    metadata:
      labels:
        app: course-app
    spec:
      containers:
        - name: course-app
          image: viktor1sss/course-app:lesson-07
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: course-app-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: course-app-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-course-app
  template:
    metadata:
      labels:
        app: redis-course-app
    spec:
      containers:
        - name: redis-course-app
          image: redis:alpine
          ports:
            - containerPort: 6379
